### ISSUE TITLE
WPEFramework crash when shutting down

### ISSUE THREAD

**Issue by goruklu** [rdkcentral/Thunder#60]
We see the following crash when exiting from WPEFramework service:
```
Core was generated by `WPEFramework -c /etc/WPEFramework/config.json'.
Program terminated with signal 11, Segmentation fault.
#0  0xb6eb6c5a in WPEFramework::RPC::Administrator::~Administrator (this=0xb6ecc754 <WPEFramework::RPC::Administrator::Instance()::systemAdministrator>, __in_chrg=<optimized out>)
    at /usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r0/git/Source/protocols/Administrator.cpp:38
38                  delete proxy.second;
(gdb) bt
#0  0xb6eb6c5a in WPEFramework::RPC::Administrator::~Administrator (this=0xb6ecc754 <WPEFramework::RPC::Administrator::Instance()::systemAdministrator>, __in_chrg=<optimized out>)
    at /usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r0/git/Source/protocols/Administrator.cpp:38
#1  0xb6cb4570 in __cxa_finalize (d=0xb6ec8138) at cxa_finalize.c:56
#2  0xb6eabb24 in __do_global_dtors_aux () from /home/build/arrisXi6_2003/build-arrisxi6/tmp/sysroots/arrisxi6/usr/lib/libWPEFrameworkProtocols.so.1.0.0
#3  0xb6f1d024 in _dl_fini () at dl-fini.c:252
#4  0xb6cb42bc in __run_exit_handlers (status=0, listp=0xb6d5e520 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#5  0xb6cb431a in __GI_exit (status=<optimized out>) at exit.c:104
#6  0xb6ca44aa in __libc_start_main (main=0x0, argc=0, argv=0xb6f30000, init=<optimized out>, fini=0x5d695 <__libc_csu_fini>, rtld_fini=0xb6f1cddd <_dl_fini>, stack_end=0xbe805d14) at libc-start.c:319
#7  0x00032994 in _start () at ../ports/sysdeps/arm/start.S:124
```

- This is reproducible on the desktop linux with the latest master branch.
- crash happens even without any plugins loaded.

**Comment by pwielders** [comment]
Fixed: https://github.com/rdkcentral/Thunder/pull/62

**Comment by goruklu** [comment]
@pwielders I still see this crash happening. #62 did not fix it for me

**Comment by goruklu** [comment]
Nevermind, had to re-build cmake&make under Tools in order to install the new version of ProxyStubGenerator.
After doing that , crash is not seen, thanks!
